=== donyamohamed/Xml-C-project/courseSchema2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:simpleType name="sIdvalidate">
		<xs:restriction base="xs:string">
			<xs:pattern value="\d{1|2}(S)"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="tIdvalidate">
		<xs:restriction base="xs:string">
			<xs:pattern value="\d{1|2}(T)"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="cIdvalidate">
		<xs:restriction base="xs:string">
			<xs:pattern value="\d{1|2}(C)"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="namevalidate">
		<xs:restriction base="xs:string">
			<xs:pattern value="[a-zA-Z]{3,}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="statusenum">
		<xs:restriction base="xs:integer">
			<xs:enumeration value="1"/>
			<xs:enumeration value="-1"/>
			<xs:enumeration value="0"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="integer">
		<xs:restriction base="xs:integer">
			<xs:minInclusive value="1"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="Courses">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="course" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="course" type="CourseType"/>
	<xs:complexType name="CourseType">
		<xs:sequence>
			<xs:element name="courseId" type="cIdvalidate"/>
			<xs:element name="courseName" type="namevalidate"/>
			<xs:element name="sessionsNumber" type="integer"/>
			<xs:element name="description" type="xs:string"/>
			<xs:element name="teacherId" type="TeacherType" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="TeacherType">
		<xs:sequence>
			<xs:element name="studentId" type="StudentType" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="id" type="tIdvalidate" use="required"/>
	</xs:complexType>
	<xs:complexType name="StudentType">
		<xs:sequence>
			<xs:element ref="session" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="id" type="sIdvalidate" use="required"/>
	</xs:complexType>
	<xs:element name="session" type="SessionType"/>
	<xs:complexType name="SessionType">
		<xs:sequence>
			<xs:element name="date" type="xs:date"/>
			<xs:element name="status" type="statusenum"/>
		</xs:sequence>
	</xs:complexType>
	<xs:attributeGroup name="IdAttributes">
		<xs:attribute name="id" type="sIdvalidate"/>
	</xs:attributeGroup>
	<xs:attributeGroup name="TeacherIdAttributes">
		<xs:attribute name="id" type="tIdvalidate"/>
	</xs:attributeGroup>
</xs:schema>

=== donyamohamed/Xml-C-project/courses.xml
<?xml version="1.0" encoding="UTF-8"?>
<Courses xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="courseSchema2.xsd">
	<course>
		<courseId>1C</courseId>
		<courseName>Xml</courseName>
		<sessionsNumber>4</sessionsNumber>
		<description>drftgyhujk</description>
		<teacherId id="1T">
			<studentId id="1S">
				<session>
					<date>2022-03-22</date>
					<status>1</status>
				</session>
				<session>
					<date>2022-03-24</date>
					<status>-1</status>
				</session>
				<session>
					<date>2022-03-25</date>
					<status>-1</status>
				</session>
				<session>
					<date>2022-03-26</date>
					<status>-1</status>
				</session>
			</studentId>
			<studentId id="2S">
				<session>
					<date>2022-03-24</date>
					<status>1</status>
				</session>
				<session>
					<date>2022-03-25</date>
					<status>-1</status>
				</session>
				<session>
					<date>2022-03-26</date>
					<status>-1</status>
				</session>
				<session>
					<date>2022-03-28</date>
					<status>-1</status>
				</session>
			</studentId>
		</teacherId>
		<teacherId id="1T">
			<studentId id="1S">
				<session>
					<date>2023-04-04</date>
					<status>1</status>
				</session>
				<session>
					<date>2023-04-05</date>
					<status>-1</status>
				</session>
				<session>
					<date>2023-04-06</date>
					<status>-1</status>
				</session>
				<session>
					<date>2023-04-07</date>
					<status>-1</status>
				</session>
			</studentId>
			<studentId id="3S">
				<session>
					<date>2024-01-04</date>
					<status>1</status>
				</session>
				<session>
					<date>2024-01-05</date>
					<status>-1</status>
				</session>
				<session>
					<date>2024-01-06</date>
					<status>-1</status>
				</session>
				<session>
					<date>2024-01-07</date>
					<status>-1</status>
				</session>
			</studentId>
		</teacherId>
	</course>
</Courses>
