=== donyamohamed/Xml-C-project/Attendance Management System/backup/classSchema2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">

    <xs:simpleType name="sIdvalidate">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d{1|2}(S)"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="tIdvalidate">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d{1|2}(T)"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="cIdvalidate">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d{1|2}(C)"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="csIdvalidate">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d{1|2}(CS)"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="statusenum">
        <xs:restriction base="xs:integer">
            <xs:enumeration value="1"/>
            <xs:enumeration value="-1"/>
            <xs:enumeration value="0"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="integer">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="1"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="Classes">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="class" maxOccurs="unbounded" type="ClassType"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="ClassType">
        <xs:sequence>
            <xs:element name="classId" type="csIdvalidate"/>
            <xs:element name="courseId" type="cIdvalidate"/>
            <xs:element name="teacherId" maxOccurs="unbounded" type="tIdvalidate"/>
            <xs:element name="studentId" maxOccurs="unbounded" type="StudentType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="StudentType">
        <xs:sequence>
            <xs:element name="session" maxOccurs="unbounded" type="SessionType"/>
        </xs:sequence>
        <xs:attribute name="id" type="sIdvalidate" use="required"/>
    </xs:complexType>

    <xs:complexType name="SessionType">
        <xs:sequence>
            <xs:element name="date" type="xs:date"/>
            <xs:element name="status" type="statusenum"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== donyamohamed/Xml-C-project/class.xml
<?xml version="1.0" encoding="UTF-8"?>
<Classes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\Users\Orginal\Downloads\Xml-C-project\Xml-C-project-main\classSchema2.xsd">
	<class>
		<classId>1CS</classId>
		<courseId>1C</courseId>
		<teacherId >1T</teacherId>
		<studentId id="1S">
			<session>
				<date>2022-03-22</date>
				<status>1</status>
			</session>
			<session>
				<date>2022-03-24</date>
				<status>-1</status>
			</session>
			<session>
				<date>2022-03-25</date>
				<status>-1</status>
			</session>
			<session>
				<date>2022-03-26</date>
				<status>-1</status>
			</session>
		</studentId>
		
	</class>
	<class>
		<classId>1CS</classId>
		<courseId>2C</courseId>
		<teacherId >2T</teacherId>
		<studentId id="1S">
			<session>
				<date>2023-04-04</date>
				<status>1</status>
			</session>
			<session>
				<date>2023-04-05</date>
				<status>-1</status>
			</session>
			<session>
				<date>2023-04-06</date>
				<status>-1</status>
			</session>
		</studentId>
		<studentId id="3S">
			<session>
				<date>2023-04-04</date>
				<status>1</status>
			</session>
			<session>
				<date>2023-04-05</date>
				<status>-1</status>
			</session>
			<session>
				<date>2023-04-06</date>
				<status>-1</status>
			</session>
		</studentId>
	</class>
</Classes>
