=== donyamohamed/Xml-C-project/Attendance Management System/backup/courseSchema2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:simpleType name="cIdvalidate">
		<xs:restriction base="xs:string">
			<xs:pattern value="\d{1|2}(C)"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="namevalidate">
		<xs:restriction base="xs:string">
			<xs:pattern value="[a-zA-Z]{3,}"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="integer">
		<xs:restriction base="xs:integer">
			<xs:minInclusive value="1"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="Courses">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="course" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="course" type="CourseType"/>
	<xs:complexType name="CourseType">
		<xs:sequence>
			<xs:element name="courseId" type="cIdvalidate"/>
			<xs:element name="courseName" type="namevalidate"/>
			<xs:element name="sessionsNumber" type="integer"/>
			<xs:element name="description" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== donyamohamed/Xml-C-project/Attendance Management System/courses.xml
<?xml version="1.0" encoding="UTF-8"?>
<Courses xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="courseSchema2.xsd">
	<course>
		<courseId>1C</courseId>
		<courseName>Xml</courseName>
		<sessionsNumber>4</sessionsNumber>
		<description>crash course about xml</description>
	</course>
	<course>
		<courseId>2C</courseId>
		<courseName>Java</courseName>
		<sessionsNumber>3</sessionsNumber>
		<description>learn fundemuntal for jave</description>
	</course>
		<course>
		<courseId>3C</courseId>
		<courseName>MVC</courseName>
		<sessionsNumber>6</sessionsNumber>
		<description>about design pattern</description>
	</course>
		<course>
		<courseId>4C</courseId>
		<courseName>Node</courseName>
		<sessionsNumber>4</sessionsNumber>
		<description>learn about backend</description>
	</course>
		<course>
		<courseId>5C</courseId>
		<courseName>Sql</courseName>
		<sessionsNumber>6</sessionsNumber>
		<description>more about database</description>
	</course>
</Courses>
