=== donyamohamed/Xml-C-project/Attendance Management System/backup/usershema2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:simpleType name="idvalidate">
		<xs:restriction base="xs:string">
			<xs:pattern value="\d{1|2}(T|S|A){1}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="namevalidate">
		<xs:restriction base="xs:string">
			<xs:pattern value="[a-zA-Z]{3,}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="agevalidate">
		<xs:restriction base="xs:integer">
			<xs:minInclusive value="18"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="emailvalidate">
		<xs:restriction base="xs:string">
			<xs:pattern value="[a-zA-Z]{3,}\d{0,}@[a-zA-Z]{3,}.[a-zA-Z]{3}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="passwordvalidate">
		<xs:restriction base="xs:string">
			<xs:pattern value="[A-Za-z]{3,}($|@|#|%)\d{2,}|($|@|#|%)[A-Za-z]{3,}\d{2,}|[A-Za-z]{3,}\d{2,}($|@|#|%)"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="phonevalidate">
		<xs:restriction base="xs:string">
			<xs:pattern value="(011|012|015|010)\d{8}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="roleenum">
		<xs:restriction base="xs:string">
			<xs:enumeration value="admin"/>
			<xs:enumeration value="student"/>
			<xs:enumeration value="teacher"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="Users">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="user" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="user" type="userType"/>
	<xs:complexType name="userType">
		<xs:sequence>
			<xs:element ref="id"/>
			<xs:element ref="fname"/>
			<xs:element ref="lname"/>
			<xs:element ref="age"/>
			<xs:element ref="email"/>
			<xs:element ref="password"/>
			<xs:element ref="phone"/>
			<xs:element name="address" type="xs:string"/>
		</xs:sequence>
		<xs:attribute name="role" type="roleenum"/>
	</xs:complexType>
	<xs:element name="id" type="idvalidate"/>
	<xs:element name="fname" type="namevalidate"/>
	<xs:element name="lname" type="namevalidate"/>
	<xs:element name="age" type="agevalidate"/>
	<xs:element name="email" type="emailvalidate"/>
	<xs:element name="password" type="passwordvalidate"/>
	<xs:element name="phone" type="phonevalidate"/>
</xs:schema>

=== donyamohamed/Xml-C-project/users.xml
<?xml version="1.0" encoding="UTF-8"?>
<Users xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="usershema2.xsd">
  <user role="admin">
    <id>1A</id>
    <fname>Asmaa</fname>
    <lname>Omar</lname>
    <age>22</age>
    <email>asmaa23@gmail.com</email>
    <password>@Zab890</password>
    <phone>01101234565</phone>
    <address>Damitta</address>
  </user>
</Users>
